Add success and error handling for backup creation

diff --git a/bash/backup-script b/bash/backup-script
--- a/bash/backup-script
+++ b/bash/backup-script
@@ -82,3 +82,11 @@ else
         tar -zvcf "${ADD_DATE_TO_FILENAME}-${2}" $1
     fi
 fi
+
+
+if [[ ! -f "$2" ]]; then
+    echo "ERROR: Could not create the backup file."
+    exit 1
+fi
+
+echo "INFO: Backup is created successfully."
