Validate remaining arguments for directory and file name

diff --git a/bash/backup-script b/bash/backup-script
--- a/bash/backup-script
+++ b/bash/backup-script
@@ -51,3 +51,20 @@ while true; do
             ;;
     esac
 done
+
+
+if [[ $# -ne 2 ]]; then
+    usage
+    exit 1
+fi
+
+if [[ ! -d "$1" ]]; then
+    echo "ERROR: $1 should be a directory."
+    exit 1
+fi
+
+if [[ "$2" != *.tar.gz ]]; then
+    echo "ERROR: $2 should be something with .tar.gz extension."
+    exit 1
+fi
+
